name: OPAVEDA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fcff'
    - '#231f20'
    - '#eabba4'
    - '#7b7537'
    - '#6c3a27'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
