name: OPAVEDA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d5dee3'
    - '#a7adad'
    - '#493802'
    - '#8c8d87'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
